# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_id',
            field=models.CharField(default=123, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='student_id',
            field=models.CharField(default=123, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
