# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tree', '0002_auto_20170422_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='node_id',
        ),
        migrations.AddField(
            model_name='genre',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
